---
kind: pipeline
type: docker
name: pipeline

steps:
- name: publish latest
  image: plugins/docker
  settings:
    repo: pingu/rancher-cicd-deployment
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master ]

- name: publish tag
  image: plugins/docker
  settings:
    repo: pingu/rancher-cicd-deployment
    tags: ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    event:
      - tag
